# Form-Maker-Synx1200
import time
import random
#Form Maker
FileName = input("Form_Name: ")
FN = input("Full_Name: ")
Age = input("Your_Age: ")
Bday = input("Your_Birthday: ")
Cell_Num = input("Phone_Number: ")
Sex = input("Sex: ")
print("Wait A Few Seconds")
time.sleep(2.0)
print("Making Form.")
time.sleep(0.2)
print("Making Form..")
time.sleep(0.2)
print("Making Form...")
time.sleep(0.2)
print("Making Form....")
time.sleep(0.2)
print("Making Form.....")
time.sleep(0.2)
print("Making Form......")
time.sleep(0.2)
print("Making Form.......")
time.sleep(0.2)
print("Making Form........")
time.sleep(0.2)
print("Making Form.........")
time.sleep(0.2)
print("Making Form..........")
print("Making Form...........")
time.sleep(0.2)
print("Making Form............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(0.2)
print("Making Form.............")
time.sleep(2.0)

for i in range(51):
	print(i*"|",i*2,"%",end='\r')
	time.sleep(random.uniform(0.01,0.3))
	
print("Loading Form..")
time.sleep(0.9)



e = ("Sex: ")
d = ("Phone Number")
c = ("Birth Date: ")
b = ("Age: ")
a = ("Full Name: ")

print(" ")
print("|"," "," "," "," "," ",FileName,"File")
print("|",a,FN)
print("|","-","-","-","-","-","-","-","-","-","-","-","-")
print("|",b,Age)
print("|","-","-","-","-","-","-","-","-","-","-","-","-")
print("|",c,Bday)
print("|","-","-","-","-","-","-","-","-","-","-","-","-")
print("|",d,Cell_Num)
print("|","-","-","-","-","-","-","-","-","-","-","-","-")
print("|",e,Sex)
print("|","-","-","-","-","-","-","-","-","-","-","-","-")

print("Form Has Been Completed")
print("Thanks For Using The Jamir's Form Maker See You Next Time")
